import type { Product, GenerationJob } from '@/db/schema';

export const demoProducts: Product[] = [
  { id: 1, code: '240101', marketplace: 'coupang', sourceUrl: 'https://www.coupang.com/vp/products/240101', affiliateUrl: 'https://www.coupang.com/', name: '접이식 무선 미니 선풍기', description: '책상 위와 여행 가방에 부담 없이 넣는 충전식 미니 선풍기입니다.', imageUrl: 'https://images.unsplash.com/photo-1591091869911-2c1c12e5a3a4?auto=format&fit=crop&w=1000&q=85', videoUrl: null, status: 'ready', disclosure: '제휴 링크를 통한 구매 시 수수료를 받을 수 있습니다.', createdAt: new Date('2026-09-01'), updatedAt: new Date('2026-09-02') },
  { id: 2, code: '240102', marketplace: 'temu', sourceUrl: 'https://www.temu.com/', affiliateUrl: 'https://www.temu.com/', name: '데스크 케이블 정리 트레이', description: '책상 아래 선을 깔끔하게 숨기고 필요한 케이블만 꺼내 쓰는 정리 트레이입니다.', imageUrl: 'https://images.unsplash.com/photo-1586953208448-b95a79798f07?auto=format&fit=crop&w=1000&q=85', videoUrl: null, status: 'queued', disclosure: '제휴 링크를 통한 구매 시 수수료를 받을 수 있습니다.', createdAt: new Date('2026-08-28'), updatedAt: new Date('2026-08-28') },
  { id: 3, code: '240103', marketplace: 'aliexpress', sourceUrl: 'https://www.aliexpress.com/', affiliateUrl: 'https://www.aliexpress.com/', name: '컴팩트 여행용 파우치 세트', description: '작은 소지품을 카테고리별로 나눠 담기 좋은 여행용 파우치 세트입니다.', imageUrl: 'https://images.unsplash.com/photo-1553062407-98eeb64c6a62?auto=format&fit=crop&w=1000&q=85', videoUrl: null, status: 'draft', disclosure: '제휴 링크를 통한 구매 시 수수료를 받을 수 있습니다.', createdAt: new Date('2026-08-25'), updatedAt: new Date('2026-08-25') },
];
export const demoJobs: GenerationJob[] = [];
const marketplaceDomains: Record<string, string> = { coupang: 'coupang.com', temu: 'temu.com', aliexpress: 'aliexpress.com' };
export function marketplaceFromUrl(value: string) { if (!isSafeExternalUrl(value)) throw new Error('안전한 http(s) 상품 URL을 입력해 주세요.'); const host = new URL(value).hostname.replace(/^www\./, ''); if (host === 'coupang.com' || host.endsWith('.coupang.com')) return 'coupang'; if (host === 'temu.com' || host.endsWith('.temu.com')) return 'temu'; if (host === 'aliexpress.com' || host.endsWith('.aliexpress.com')) return 'aliexpress'; throw new Error('쿠팡, 테무, 알리익스프레스 상품 URL만 등록할 수 있습니다.'); }
export function isSafeExternalUrl(value: string) { try { const parsed = new URL(value); if (!['http:', 'https:'].includes(parsed.protocol) || parsed.username || parsed.password) return false; const host = parsed.hostname.toLowerCase(); if (['localhost', '127.0.0.1', '::1'].includes(host) || host.endsWith('.local')) return false; if (/^(10\.|127\.|192\.168\.|172\.(1[6-9]|2\d|3[01])\.)/.test(host)) return false; return true; } catch { return false; } }
export function isMarketplaceUrl(value: string, marketplace: string) { if (!isSafeExternalUrl(value)) return false; try { const host = new URL(value).hostname.replace(/^www\./, '').toLowerCase(); const domain = marketplaceDomains[marketplace]; return Boolean(domain && (host === domain || host.endsWith(`.${domain}`))); } catch { return false; } }
export function isSafeAffiliateUrl(value: string, marketplace: string) { return isMarketplaceUrl(value, marketplace); }
export function now() { return new Date(); }
