Add-Type -AssemblyName System.Windows.Forms
Add-Type -AssemblyName System.Drawing
$root=Split-Path -Parent $PSScriptRoot; $file=Join-Path $root '.env.local'
$f=New-Object Windows.Forms.Form; $f.Text='PrizeNine 자동화 설정'; $f.Size=New-Object Drawing.Size(560,560); $f.StartPosition='CenterScreen'
$labels=@("Trigger secret","Google Apps Script URL","Notification email","Telegram Bot Token","Telegram Chat ID","Topview API Key"); $keys=@("TRIGGER_SECRET","GOOGLE_APPS_SCRIPT_URL","NOTIFY_EMAIL","TELEGRAM_BOT_TOKEN","TELEGRAM_CHAT_ID","TOPVIEW_API_KEY"); $boxes=@{}
for($i=0;$i -lt $labels.Count;$i++){ $l=New-Object Windows.Forms.Label; $l.Text=$labels[$i]; $l.Location=New-Object Drawing.Point(25,(25+$i*55)); $l.AutoSize=$true; $f.Controls.Add($l); $t=New-Object Windows.Forms.TextBox; $t.Location=New-Object Drawing.Point(190,(20+$i*55)); $t.Size=New-Object Drawing.Size(330,28); if($keys[$i] -match 'TOKEN|KEY|SECRET'){$t.PasswordChar='*'}; $f.Controls.Add($t); $boxes[$keys[$i]]=$t }
$boxes['TRIGGER_SECRET'].Text=[guid]::NewGuid().ToString('N')
$save=New-Object Windows.Forms.Button; $save.Text="Save settings"; $save.Location=New-Object Drawing.Point(120,420); $save.Size=New-Object Drawing.Size(150,40); $save.Add_Click({ $v=@("TRIGGER_SECRET=$($boxes.TRIGGER_SECRET.Text)","INGEST_TOKEN=$($boxes.TRIGGER_SECRET.Text)","GOOGLE_APPS_SCRIPT_URL=$($boxes.GOOGLE_APPS_SCRIPT_URL.Text)","NOTIFY_EMAIL=$($boxes.NOTIFY_EMAIL.Text)","TELEGRAM_BOT_TOKEN=$($boxes.TELEGRAM_BOT_TOKEN.Text)","TELEGRAM_CHAT_ID=$($boxes.TELEGRAM_CHAT_ID.Text)","TOPVIEW_API_KEY=$($boxes.TOPVIEW_API_KEY.Text)); Set-Content -LiteralPath $file -Value ($v -join ([Environment]::NewLine)) -Encoding utf8; [Windows.Forms.MessageBox]::Show("Settings saved", "PrizeNine") }); $f.Controls.Add($save)
$testUrl=New-Object Windows.Forms.TextBox; $testUrl.Location=New-Object Drawing.Point(25,475); $testUrl.Size=New-Object Drawing.Size(350,28); $f.Controls.Add($testUrl)
$test=New-Object Windows.Forms.Button; $test.Text="Run test"; $test.Location=New-Object Drawing.Point(390,470); $test.Size=New-Object Drawing.Size(130,36); $test.Add_Click({ try { $b=@{text=$testUrl.Text;source="gui-test"}|ConvertTo-Json; $r=Invoke-WebRequest -UseBasicParsing -Method Post -Uri "https://prizenine.vercel.app/api/trigger" -Headers @{Authorization="Bearer $($boxes.TRIGGER_SECRET.Text)"} -ContentType "application/json" -Body $b; [Windows.Forms.MessageBox]::Show("Success: $($r.StatusCode)","PrizeNine") } catch { [Windows.Forms.MessageBox]::Show("Failed: $($_.Exception.Message)","PrizeNine") } }); $f.Controls.Add($test)
$f.ShowDialog() | Out-Null
